server:
  port: 8080
spring:
  application:
    name: cloud-demo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/S1ow/cloud-demo.git
          search-paths: cloud-demo-repo


