server:
  port: 8081

spring:
  application:
    name: cloudprovider
  cloud:
    config:
      uri: http://${config.server.ip}:${config.server.port}
      name: cloudprovider
      profile: ${app.profile:test}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.99.100:3306/blog?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: 123456

mybatis:
  typeAliasesPackage: com.domcj.provider.entity
  mapperLocations: classpath:mapper/*.xml