server:
  port: 8090

spring:
  application:
    name: cloudconsumer
  cloud:
    config:
      uri: http://${config.server.ip}:${config.server.port}
      name: cloudconsumer
      profile: ${app.profile:test}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
cloudservice:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 10000